spring.application.name=Employee_Information_System
server.port=8080

spring.datasource.url=jdbc:sqlserver://localhost:1434;databaseName=Employees_Info;encrypt=true;trustServerCertificate=true
spring.datasource.username=sa
spring.datasource.password=SqlServer@123


spring.jpa.show.sql=true
spring.jpa.hibernate.ddl-auto=validate

